### ISSUE TITLE
TLS Settings not working on Zabbix 3.2

### ISSUE THREAD

**Issue by frennkie** [dj-wasabi/ansible-zabbix-agent#55] opened 2017-01-04 17:42 UTC
I just started using this Ansible Role for my Zabbix 3.2 installation and noticed that none of the TLS settings are writen to the zabbix_agentd.conf file.
As I won't be going back to anything older than Zabbix 3.0 I removed the version check:
https://github.com/dj-wasabi/ansible-zabbix-agent/blob/master/templates/zabbix_agentd.conf.j2#L228

But it might be good if you could fix this in the role (also for people on <3.0).

**Comment by frennkie** [comment] 2017-01-04 20:36
This change seems to address the same issue:
https://github.com/chibacityblues/ansible-zabbix-agent/commit/cb5c50c21decf134faab30792a4686e23720f8fe

**Comment by dj-wasabi** [comment] 2017-01-09 13:20
Thanks, will take a look at it.

**Comment by dj-wasabi** [comment] 2017-01-09 13:36
I just pushed an fix for this to Github. Can you validate if this works?

**Comment by frennkie** [comment] 2017-01-09 15:37
I already copied @chibacityblues solution which uses https://docs.ansible.com/ansible/playbooks_tests.html#version-comparison and is working for me.
But from looking at your changes that should also work... it'll give it a try later on.

**Comment by willwh** [comment] 2017-01-26 16:01
Hey @dj-wasabi thanks for your work on this, it was really helpful.

I can confirm that your changes in your `master` branch do not work with Zabbix 3.2, at all.

As mentioned though; https://github.com/chibacityblues/ansible-zabbix-agent/commit/cb5c50c21decf134faab30792a4686e23720f8fe works beautifully. (Which is what I'm using now)

**Comment by dj-wasabi** [comment] 2017-08-26 13:02
Is this still an issue? Since this morning, the role uses the `version_compare` filter.

**Comment by chibacityblues** [comment] 2017-08-28 06:17
I don't think so - my PR got merged a few weeks back.

**Comment by dj-wasabi** [comment] 2017-08-28 09:13
Ok, thank you. Will close this issue.

**Closed by dj-wasabi** 2017-08-28 09:13 UTC
Labels: bug
