### ISSUE TITLE
FAILED - RETRYING: Install local python-netaddr package

### ISSUE THREAD

**Issue by jakko10** [dj-wasabi/ansible-zabbix-agent#252] opened 2019-08-12 08:31 UTC
Hi,

Looks like it's unable to find python-netaddr even though it is installed.
Also pip is installed.

How does one go about resolving this issue?

` TASK [dj-wasabi.zabbix-agent : Install local python-netaddr package] ****************************************************************************************
FAILED - RETRYING: Install local python-netaddr package (3 retries left).
fatal: [someserver -> localhost]: FAILED! => {"attempts": 3, "changed": false, "msg": "Unable to find any of pip2, pip to use.  pip needs to be installed."}
PLAY RECAP **************************************************************************************************************************************************
someserver       : ok=9    changed=0    unreachable=0    failed=1    skipped=19   rescued=0    ignored=0  `

**Comment by dj-wasabi** [comment] 2019-08-12 15:26
Hi @jakko10 

And pip is installed on the host on which you are running ansible from, so `localhost`?

**Comment by lebe-dev** [comment] 2019-09-11 09:40
OS: CentOS Linux release 7.6.1810 (Core)

```
yum list installed | grep python-netaddr
Repository zabbix-non-supported is listed more than once in the configuration
python-netaddr.noarch                 0.7.5-9.el7                     @YANDEX
```

and pip:

```
pip list | grep netaddr
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020.blablabla...
netaddr                          0.7.19
```

**How to reproduce:**

I run playbook:

```
---
- hosts: internal-services
  become: yes
  roles:
    - dj-wasabi.zabbix-agent
```

vars defined:
```
zabbix_agent_serveractive: our-zabbix-server
zabbix_version: 4.0
zabbix_agent_startagents: 0
zabbix_agent_listeninterface: localhost
zabbix_agent_interfaces: localhost
```

What i've got:

```
> ansible-playbook -K -b -i our-inventory-file internal-services.yml

TASK [dj-wasabi.zabbix-agent : Install local python-netaddr package] ***************************************************************************************************************************************
FAILED - RETRYING: Install local python-netaddr package (3 retries left).
FAILED - RETRYING: Install local python-netaddr package (2 retries left).
FAILED - RETRYING: Install local python-netaddr package (1 retries left).
fatal: [kamis-insurance -> localhost]: FAILED! => {"attempts": 3, "changed": false, "module_stderr": "Sorry, try again.\n[sudo via ansible, key=cxxfnrbsumzgowbgtztpzsgslepptpot] password:\nsudo: 1 incorrect password attempt\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
```

**Comment by ynott** [comment] 2019-09-20 02:48
I found the same error. @jakko10 mentioned.

but, I installed python2-pip
```
yum install python2-pip.noarch
```
then I retryed to run ansible-playbook, 
It looks like OK,but next error happend.

```
TASK [zabbix-agent : Install local python-netaddr package] **************************************************************************************************************************
changed: [127.0.0.1 -> localhost]

TASK [zabbix-agent : Set default ip address for zabbix_agent_ip] ********************************************************************************************************************
ok: [127.0.0.1]

TASK [zabbix-agent : Get Total Private IP Addresses] ********************************************************************************************************************************
fatal: [127.0.0.1]: FAILED! => {"msg": "The ipaddr filter requires python's netaddr be installed on the ansible controller"}
```

I install zabbix-agent locally.
This is my playbook.
```
---
- hosts: all
  connection: local
  remote_user: root
  sudo: yes
  gather_facts: yes
  roles:
    - zabbix-agent
  vars:
    zabbix_agent_server: xx.xx.xx.xx,yy.yy.yy.yy
    zabbix_agent_serveractive: xx.xx.xx.xx,yy.yy.yy.yy
    zabbix_version: 4.0
    zabbix_repo: zabbix
    zabbix_agent_allowroot: 1
```

* Ansible Version
```
ansible 2.8.4
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Aug  7 2019, 00:51:29) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
```

**Comment by ynott** [comment] 2019-09-20 02:56
I'm not sure, when I tried running Ansible-playbook again, the above error disappeared.
Maybe it was just a timing issue for loading the library.

I thank you for your cooperation.

**Comment by dj-wasabi** [comment] 2019-10-22 17:45
Will close this issue as (possible) workaround was suggested.

**Closed by dj-wasabi** 2019-10-22 17:45 UTC
Labels: More information needed

**Comment by alebeta90** [comment] 2019-10-29 16:47
The problem is persisting on my side using Fedora 30 as localhost

```
ansible 2.8.5
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/alebeta/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.7.4 (default, Jul  9 2019, 16:32:37) [GCC 9.1.1 20190503 (Red Hat 9.1.1-1)]
```

I have netaddr installed using pip3 but somehow I still get the message

`FAILED! => {"msg": "The ipaddr filter requires python's netaddr be installed on the ansible controller"}`

There is some information I could provide in order to debug this issue?

All the best

**Comment by myjapan** [comment] 2020-01-22 09:45
Hello, same problem here on Ubuntu 18.04
`FAILED! => {"msg": "The ipaddr filter requires python's netaddr be installed on the ansible controller"}`

Netaddr installed using apt
netaddr shell 0.7.19

**Comment by dj-wasabi** [comment] 2020-01-24 08:48
Hi @myjapan & @alebeta90 

Did you set the `ansible_python_interpreter` to the correct python binary? Maybe you have different versions installed or Ansible is not correctly to determine which path is used.
